#!/bin/bash
testusr=fxdhdu
if grep $testusr /etc/passwd
then
	echo The bash files for user $testusr are:
	ls -a /home/$testusr/.b*
else 
	echo "The user name $testusr does not exist on this system"
fi
